#include "SfzExporter.h"

namespace
{
    juce::String quoteIfNeeded (const juce::String& path)
    {
        return path.containsChar (' ') ? "\"" + path + "\"" : path;
    }

    juce::String samplePathFor (const SampleZone& z, const juce::File& destinationFile, bool relative)
    {
        if (z.sampleFile == juce::File())
            return {};

        if (relative && destinationFile != juce::File())
        {
            const auto rel = z.sampleFile.getRelativePathFrom (destinationFile.getParentDirectory());
            return rel.replaceCharacter ('\\', '/');
        }
        return z.sampleFile.getFullPathName().replaceCharacter ('\\', '/');
    }

    void appendRegion (juce::String& out, const SampleZone& z, const juce::File& destinationFile,
                        const SfzExporter::Options& opts, int transposeSemitones, float extraGainDb,
                        float extraTuneCents)
    {
        out << "<region>\n";

        const auto samplePath = samplePathFor (z, destinationFile, opts.useRelativeSamplePaths);
        if (samplePath.isNotEmpty())
            out << "sample=" << quoteIfNeeded (samplePath) << "\n";

        out << "lokey=" << z.lowKey << " hikey=" << z.highKey
            << " pitch_keycenter=" << z.rootKey << "\n";
        out << "lovel=" << z.lowVelocity << " hivel=" << z.highVelocity << "\n";

        // Instrument-level transpose/gain are baked into each region here —
        // see SfzExporter.h for why the model doesn't try to express a
        // separate global scope in the generated file.
        const float tune = z.tuneCents + extraTuneCents;
        if (tune != 0.0f)
            out << "tune=" << juce::String (tune, 2) << "\n";
        if (transposeSemitones != 0)
            out << "transpose=" << transposeSemitones << "\n";

        const float volume = z.gainDb + extraGainDb;
        if (volume != 0.0f)
            out << "volume=" << juce::String (volume, 2) << "\n";
        if (z.pan != 0.0f)
            out << "pan=" << juce::String (z.pan * 100.0f, 1) << "\n";

        if (z.sampleStart != 0)
            out << "offset=" << (juce::int64) z.sampleStart << "\n";
        if (z.sampleEnd >= 0)
            out << "end=" << (juce::int64) z.sampleEnd << "\n";

        out << "loop_mode=" << loopModeToOpcodeValue (z.loopMode) << "\n";
        if (z.loopMode != LoopMode::noLoop && z.loopStart >= 0 && z.loopEnd >= 0)
            out << "loop_start=" << (juce::int64) z.loopStart
                << " loop_end=" << (juce::int64) z.loopEnd << "\n";

        out << "ampeg_attack=" << juce::String (z.attackSeconds, 4)
            << " ampeg_decay=" << juce::String (z.decaySeconds, 4)
            << " ampeg_sustain=" << juce::String (z.sustainLevel * 100.0f, 2)
            << " ampeg_release=" << juce::String (z.releaseSeconds, 4) << "\n";

        if (z.filterCutoffHz < 20000.0f)
            out << "cutoff=" << juce::String (z.filterCutoffHz, 1) << "\n";
        if (z.filterResonance > 0.0f)
            out << "resonance=" << juce::String (z.filterResonance * 40.0f, 2) << "\n";

        if (z.group != 0)      out << "group=" << z.group << "\n";
        if (z.offBy != 0)      out << "off_by=" << z.offBy << "\n";
        if (z.sequenceLength > 1)
            out << "seq_position=" << z.sequencePosition << " seq_length=" << z.sequenceLength << "\n";

        // Custom colour override — written as juce::Colour::toString()
        // (an 8-digit ARGB hex string) via the dysekt_zone_color custom
        // opcode; see SfzImporter for the read side. Omitted entirely when unset
        // so a zone with no override doesn't pick up a colour on reload
        // that the user never actually chose.
        if (z.hasCustomColour)
            out << "dysekt_zone_color=" << juce::Colour (z.customColourArgb).toString() << "\n";

        for (const auto& [k, v] : z.extraOpcodes)
            out << k << "=" << v << "\n";

        out << "\n";
    }
}

juce::String SfzExporter::render (const MultisamplerInstrument& instrument,
                                   const juce::File& destinationFile,
                                   Options options)
{
    juce::String out;
    out << "// Generated by METRO-UI Multisampler — do not edit by hand;\n"
        << "// re-export after editing " << instrument.name << " instead.\n\n";

    for (const auto& z : instrument.zones)
        if (z.enabled)
            appendRegion (out, z, destinationFile, options,
                          instrument.transposeSemitones, instrument.masterGainDb,
                          instrument.fineTuneCents);

    // Re-emit <curve>/<effect>/<master>/<midi> (etc.) content captured
    // verbatim on import — see MultisamplerInstrument::rawExtraHeaders and
    // SfzImporter's extractRawHeaderBlocks(). Appended after the regions so
    // a file that round-trips through MULTISAMPLER doesn't lose this
    // content, even though nothing here can edit it.
    for (const auto& block : instrument.rawExtraHeaders)
        out << block << "\n\n";

    return out;
}

bool SfzExporter::exportToFile (const MultisamplerInstrument& instrument,
                                 const juce::File& destinationFile,
                                 Options options)
{
    const auto text = render (instrument, destinationFile, options);
    return destinationFile.replaceWithText (text);
}
